default_install_hook_types: [pre-commit]

repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: "https://github.com/pre-commit/mirrors-prettier"
    rev: v2.7.1
    hooks:
      - id: prettier
        stages: [commit]
        exclude: tests\/test_.+\.

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
