default_install_hook_types: [pre-commit]

repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
      - id: black

  - repo: "https://github.com/pre-commit/mirrors-prettier"
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: tests\/test_.+\.

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.3
    hooks:
      - id: ruff
